name = "newsletter-subscription"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-10-15"

[dev]
ip = "0.0.0.0"
port = 8401

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
