version: 2
percy:
  useSystemProxy: false
  skipBaseBuild: false
snapshot:
  widths:
    - 640
    - 1024
    - 1280
  percy-css: |
    html { font-family: Filson Pro, sans-serif !important; }
  minHeight: 1024
  enableJavaScript: false
  cliEnableJavaScript: true
  disableShadowDOM: false
  responsiveSnapshotCapture: true
