name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - 'packages/workers/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy newsletter-subscription
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.25.1
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_WORKERS }}
          workingDirectory: 'packages/workers/newsletter-subscription'
