name: Run visual testing

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches:
      - master

jobs:
  visual-testing:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'visual-testing') || startsWith(github.head_ref, 'renovate/'))) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/website

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: ./packages/website/.nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install
        shell: "bash"
        run: pnpm i

      - name: Build
        shell: "bash"
        run: pnpm build

      - name: Take screenshots and upload them to Percy
        run: pnpm percy snapshot dist/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
